# Generated by Django 4.2.7 on 2024-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0003_accords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='programmes/')),
                ('date_creation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
