# Generated by Django 4.2.7 on 2024-06-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0004_programme_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='description',
            field=models.TextField(default='default_description', max_length=500),
        ),
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.TextField(default='default_description', max_length=500),
        ),
        migrations.AlterField(
            model_name='programme',
            name='subtitle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='subtitle',
            field=models.CharField(max_length=20),
        ),
    ]
