# Generated by Django 4.2.7 on 2024-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0005_programme_description_projet_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='journal_videos/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
