# Generated by Django 4.2.7 on 2024-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0006_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rapports/')),
                ('description', models.TextField(default='default_description', max_length=500)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
