# Generated by Django 4.2.7 on 2024-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0007_rapports'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapports',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='rapports_pdf/'),
        ),
    ]
