# Generated by Django 4.2.7 on 2024-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0008_rapports_fichier_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='features/')),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
