# Generated by Django 4.2.7 on 2024-06-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0010_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
