# Generated by Django 4.2.7 on 2024-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0018_alter_customuser_email_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='personnel_photos/')),
                ('linkedin', models.URLField()),
                ('category', models.CharField(choices=[('directeur', 'Directeur'), ('equipes', 'Equipes'), ('chefs_de_region', 'Chefs de région')], max_length=50)),
            ],
        ),
    ]
