# Generated by Django 4.2.7 on 2024-07-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0019_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='director_messages/')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
