# Generated by Django 3.2 on 2024-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0021_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
