# Generated by Django 3.2 on 2024-07-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0025_testimonial_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='cible',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
    ]
