# Generated by Django 3.2 on 2024-07-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0026_auto_20240729_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
