# Generated by Django 3.2 on 2024-07-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0028_educationcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationCard',
        ),
    ]
