# Generated by Django 3.2 on 2024-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0031_auto_20240730_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50)),
                ('type_peche', models.CharField(max_length=100)),
                ('date_autorisation', models.DateField()),
            ],
        ),
    ]
