# Generated by Django 3.2 on 2024-07-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0032_navire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navire',
        ),
    ]
